function test_header(hdStr :: String)
    test_divider();
    println("Testing  $hdStr")
    return nothing
end

function test_divider()
    println("-------------------")
    return nothing
end

# Put files generated by tests here
function test_dir()
	return "~/Documents/julia/test_files"
end

# ----------